<?php

namespace Aristos\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use General\GeneralBundle\Entity\Question;

/**
 * ContacctsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactsRepository extends EntityRepository
{
	
	/*
	 * get all active contacts of this user
	
	public function getActiveContacts($userId)
	{
		$qb = $this->createQueryBuilder('c')
		->select('c')
		->where('c.currentUser_id=?1 and c.status=?2')
	                    		->setParameter(1, $userId)
	                    		->setParameter(2, 'active')
	                    		->addOrderBy('c.createDate', 'DESC');
	
		return $qb->getQuery()
		->getResult();
	}*/
	
}
