<?php

namespace Aristos\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRequestRepository extends EntityRepository
{
	/*
	 * get all active requests received by  this user
	 */
	public function getActiveReceivedRequests($userId)
	{
		$qb = $this->createQueryBuilder('c')
                    ->select('c')
                    ->leftJoin('c.receiverUser', 'r')
                    ->where('r.id=?1 and 
                    		c.status!=?2 and c.status!=?3')
                    ->setParameter(1, $userId)
                    ->setParameter(2, 'accepted')
                    ->setParameter(3, 'deleted')
                    ->addOrderBy('c.createDate', 'DESC');
                    
         return $qb->getQuery()
                  ->getResult();
	}
	
	
}
