<?php

namespace Aristos\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HobbyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HobbyRepository extends EntityRepository
{
	

	/**
	 * find term
	 *
	 * @param unknown $term
	 * @param string $limit
	 * @return multitype:
	 */
	public function searchTerm($term, $limit = null)
	{
		$qb = $this->createQueryBuilder('b')
		->select('b')
		->where('b.name like ?1')
		->setParameter(1, "%$term%")
		->addOrderBy('b.id', 'DESC');
	
		if (false === is_null($limit))
			$qb->setMaxResults($limit);
	
		return $qb->getQuery()
		->getResult();
	}
	
}
