<?php

namespace Aristos\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotesRepository extends EntityRepository
{
}
