<?php

namespace Aristos\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagSexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
	public function getRelatedTags($term)
	{
		$qb = $this->createQueryBuilder('c')
		->select('c')
		->where("c.name like '%$term%'")
		->addOrderBy('c.name', 'DESC');
		
		return $qb->getQuery()
		->getResult();
	}
	
	
	/*
	*
	* get tags based on populatily, i.e times used so far
	* 
	*/
	public function getTagWeights()
	{
		$tagWeights = array();
		 
		$result = $this->createQueryBuilder('c')
		->select('c')
		->addOrderBy('c.timesUsed', 'DESC')
		->setMaxResults(10)
		->getQuery()
		->getArrayResult();
	 
		foreach ($result as $eachResult)
		{
			$tagWeights[$eachResult['name']] = $eachResult['timesUsed'];			
		}
		
		return $tagWeights;
	}
	
	/**
	 * convert a csv tags string into appropriate array for use in twig templates
	* 
	 * @param csv string $tags
	 * @return multitype:number
	 */
	public function createTagWeights($tags)
	{
		$tagWeights = array();
		
		$tags = explode(',',$tags);
		//var_dump($tagWeights);exit;
	
		foreach ($tags as $eachResult)
		{
			$tagWeights[$eachResult] = 1;
		}
	
		return $tagWeights;
	}
	
	
}
